AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'Guardfile'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  EnforcedStyle: only_raise
